### ISSUE TITLE
Trouble with storing timestamps in other timezones than UTC

### ISSUE THREAD

**Issue by kristianj** [carlcs/craft-eventtable#2]
When I'm using this plugin and my Craft settings is set to another timezone than UTC (UTC+01:00 at the moment), the timestamps is offset by the distance to UTC every time I'm storing the table contents.

My PHP installation is set to the correct timezone.

Seems there might be a problem with converting the timezones both on storing and on displaying them (I might be wrong here).

Love the plugin otherwise!

**Comment by carlcs** [comment]
Should be fixed now.
